################################# Default configuration ###################
# provide your domain here
baseURL = "https://thesis.hannesdatta.com/"
# theme
theme = "dot"
# site title
title = "Thesis companion"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 1

[[menu.main]]
name = "contact & appointments"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "Guide"
hasChildren = true

  [[menu.main]]
  parent = "Guide"
  name = "Getting started"
  url = "getting-started"
  weight = 1

  [[menu.main]]
  parent = "Guide"
  name = "Software"
  url = "skills"
  weight = 2

  [[menu.main]]
  parent = "Guide"
  name = "Meet your coach"
  url = "coach"
  weight = 3

  [[menu.main]]
  parent = "Guide"
  name = "Topic and data"
  url = "topic"
  weight = 4

  [[menu.main]]
  parent = "Guide"
  name = "Finding literature"
  url = "literature"
  weight = 5

  [[menu.main]]
  parent = "Guide"
  name = "Project pipeline"
  url = "pipeline"
  weight = 6

  [[menu.main]]
  parent = "Guide"
  name = "Thesis outline"
  url = "thesis-outline"
  weight = 7

  [[menu.main]]
  parent = "Guide"
  name = "Writing bootcamp"
  url = "manuscript"
  weight = 8


#  [[menu.main]]
#  parent = "Guide"
#  name = "Preparing your submission"
#  url = "submission"
#  weight = 7

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

#custom_css = "/my_css.css"

############################## social links ##############################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

[[params.social]]
icon = "ti-user" # themify icon pack : https://themify.me/themify-icons
link = "https://hannesdatta.com"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/hannesdatta/thesis-guide"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/hannes-datta/"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "© [Hannes Datta](https://hannesdatta.com) 2020. Theme based on [gethugothemes](https://gethugothemes.com/)."

# banner
[Languages.en.params.banner]
title = "Marketing Analytics<br>Thesis Companion"
subtitle = "A companion for your thesis trajectory<br>with Hannes Datta at Tilburg University"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = false
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."

# call to action button
[Languages.en.params.cta.button]
enable = false
label = "contact us"
link = "contact"
